### ISSUE TITLE
REACT: Render different sprites for dokis when fullness/mood levels are low or full

### ISSUE THREAD

**Issue by angely119** [CharismaticCarrots/Okidoki#118]

**Comment by kristinlam** [comment]
Suggestions:
- Happy: fullness >= 80 && and mood >= 80
- Sad: fullness + mood <= 40 (Addresses situations where one bar is high and the other is low. Encourages balancing both bars.)
- Sleeping: fullness === 0 && mood === 0
- Neutal/Idle: All other times
