### ISSUE TITLE
QUERY: Add ability to logout

### ISSUE THREAD

**Issue by kristinlam** [CharismaticCarrots/Okidoki#168]
In Tier 1, for testing the Navbar component. For Tier 2, if we get to creating user settings, this can be included in there.

**Comment by lydiakwa** [comment]
For React Query 'unmounting' is interesting. To logout, you need to clear the token in SecureStorage and clear the cache associated with React Query. You pass in a unique key for `useQuery()`, you can use that same key to call `queryClient.removeQueries('user')` clearing out the cache related to the query.
